"""
ingestion/vectorize_script.py
------------------------------
Entry point script for running the full DocStream ingestion pipeline.

This script:
1. Vectorizes all subject PDFs into whole-book and per-chapter ChromaDB stores
2. Adds image captions (generated by extract_images.py) into the same stores

Run this script once before launching the Streamlit app, and re-run it
whenever new PDFs or image captions are added.

Usage:
    python ingestion/vectorize_script.py

Prerequisites:
    - PDFs must be placed in data/class_12/<subject>/ folders
    - Run ingestion/extract_images.py first to generate image_captions.json
    - .env file must be configured with GROQ_API_KEY and OPENAI_API_KEY
"""

import sys
from pathlib import Path

# Add src/ to path so config and ingestion modules can be imported
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))  # noqa: E402

from config import SUBJECTS, DATA_DIR, ensure_directories
from ingestion.vectorize import (
    vectorize_book,
    vectorize_chapters,
    vectorize_image_captions_into_book_db,
    vectorize_image_captions_into_chapter_dbs,
)


def main():
    """Run the full ingestion pipeline for all available subjects."""

    # Ensure all required directories exist
    ensure_directories()

    for subject in SUBJECTS:
        subject_dir = DATA_DIR / subject

        # Skip subjects that have no data directory
        if not subject_dir.exists():
            print(f"\nSkipping {subject} — no data directory found at {subject_dir}")
            continue

        # Check if there are any PDFs to process
        pdfs = list(subject_dir.glob("*.pdf"))
        if not pdfs:
            print(f"\nSkipping {subject} — no PDF files found in {subject_dir}")
            continue

        print(f"\n{'='*60}")
        print(f"Processing subject: {subject.upper()}")
        print(f"Found {len(pdfs)} PDF(s)")
        print(f"{'='*60}")

        vector_db_name = f"class_12_{subject.lower()}_vector_db"

        # Step 1: Vectorize all PDFs as a whole-book index
        print(f"\n── Step 1: Vectorizing whole book ──")
        vectorize_book(
            subject_path=subject,
            vector_db_name=vector_db_name
        )

        # Step 2: Vectorize each chapter individually
        print(f"\n── Step 2: Vectorizing chapters ──")
        vectorize_chapters(subject_path=subject)

        # Step 3: Add image captions to whole-book index
        print(f"\n── Step 3: Adding image captions to book DB ──")
        vectorize_image_captions_into_book_db(
            subject=subject,
            vector_db_name=vector_db_name
        )

        # Step 4: Add image captions to chapter DBs
        print(f"\n── Step 4: Adding image captions to chapter DBs ──")
        vectorize_image_captions_into_chapter_dbs(subject=subject)

    print(f"\n{'='*60}")
    print("Ingestion complete! You can now run the app:")
    print("  streamlit run src/app/main.py")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
